### ISSUE TITLE
Two file open problem

### ISSUE THREAD

**Issue by Mara-Li** [OwnJoke/obsidian-budget-wysiwyg#2]
When you have two files open :
1. Scroll one of the file (A)
2. Edit the second (file B)
3. The switch happend on file B : the File A returns at the start.

It's very annoying because I can't use a second file as a reference (for example).

**Comment by OwnJoke** [comment]
I cannot seem to reproduce, make sure you click on the file you want to edit as whatever file you clicked on last is the one that you will type in.
