### ISSUE TITLE
[BUG] Pop-up input boxes are also captured

### ISSUE THREAD

**Issue by Borber** [OwnJoke/obsidian-budget-wysiwyg#3]
When using quickadd, the input in the popup box is also captured, and then when editing mode is enabled, the focus goes to the current note, and you have to click on the popup box again to type properly.

**Comment by OwnJoke** [comment]
I'm not going to be able to update the plugin for about a week but I'll look into it.

**Comment by Borber** [comment]
> I'm not going to be able to update the plugin for about a week but I'll look into it once I'm back.

I fixed the bug, maybe I'll give you a PR tonight

**Comment by OwnJoke** [comment]
Alright, I'm guessing the issue was that there was no placeholder text for the textbox. I know there are better ways to check and I will probably figure one out once I am back.

**Comment by OwnJoke** [comment]
Fixed in 1.0.5
