### ISSUE TITLE
Issues with renaming folders/notes while in preview mode

### ISSUE THREAD

**Issue by cakechaser** [OwnJoke/obsidian-budget-wysiwyg#6]
When I try to rename a folder in preview mode, the text that I'm typing is added to the note instead of the folder/note name.

Steps to reproduce:
- Open a note in preview mode
- Right click a folder or a note and click "Rename"
- Start typing

The active note will switch to the "edit" mode and text will be added to the note.

It's only possible to rename a folder/note when the active note is in edit mode, but it's quite tricky, since it switches to preview within 2 seconds.

**Comment by OwnJoke** [comment]
I'm pretty sure I fixed this issue in an update, try checking for updates and seeing if there are any.

**Comment by OwnJoke** [comment]
Are you renaming with the bar on the top of the file or by right clicking in the file view?

**Comment by cakechaser** [comment]
Right clicking in the file view.
Renaming in the bar on top works fine indeed.

**Comment by OwnJoke** [comment]
Alright yeah I guess I forgot to check that way of renaming.

**Comment by OwnJoke** [comment]
Fixed in 1.0.5
